import { z } from "zod";

export const kaidhaUserSchema = z.object({
  firstName: z.string().min(1, "الاسم الأول مطلوب"),
  lastName: z.string().min(1, "اسم العائلة مطلوب"),
  fatherName: z.string().min(1, "اسم الأب مطلوب"),
  grandFatherName: z.string().optional().nullable(),
  birthDate: z.string().or(z.date()).optional().nullable(),
  nationality: z.string().optional().nullable(),
  socialStatus: z.string().optional().nullable(),
  familyMembersCount: z.string().or(z.number()).optional(),
  idType: z.string().min(1, "نوع الهوية مطلوب"),
  personalIdNumber: z.string().min(1, "رقم الهوية مطلوب"),
  idExpirationDate: z.string().or(z.date()).optional().nullable(),
  phoneNumber: z.string().regex(/^\+?[0-9]{10,15}$/, "رقم الهاتف غير صحيح"),
  whatsappNumber: z.string().optional().nullable(),
  email: z.string().email("البريد الإلكتروني غير صحيح").optional().nullable(),
  homeType: z.string().optional().nullable(),
  homeNature: z.string().optional().nullable(),
  city: z.string().min(1, "المدينة مطلوبة"),
  neighborhood: z.string().optional().nullable(),
  addressDetails: z.string().optional().nullable(),
  agreed: z.boolean(),
  companyName: z.string().optional().nullable(),
  jobTitle: z.string().optional().nullable(),
  yearsOfExperience: z.string().or(z.number()).optional(),
  grossSalary: z.string().optional().nullable(),
  locationWork: z.string().optional().nullable(),
  locationHouse: z.string().optional().nullable(),
  workAddress: z.string().optional().nullable(),
  installments: z.string().optional().nullable(),
  hasAdditionalIncome: z.string().optional().nullable(),
  additionalAmount: z.string().optional().nullable(),
  incomeSource: z.string().optional().nullable(),
});

export type KaidhaUserInput = z.infer<typeof kaidhaUserSchema>;